// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package org.tdmx.server.pcs.protobuf;

public final class Broadcast {
  private Broadcast() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BroadcastMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BroadcastMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
     */
    boolean hasCacheInvalidation();
    /**
     * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
     */
    org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage getCacheInvalidation();
    /**
     * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
     */
    org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessageOrBuilder getCacheInvalidationOrBuilder();
  }
  /**
   * Protobuf type {@code BroadcastMessage}
   */
  public static final class BroadcastMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BroadcastMessage)
      BroadcastMessageOrBuilder {
    // Use BroadcastMessage.newBuilder() to construct.
    private BroadcastMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BroadcastMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BroadcastMessage defaultInstance;
    public static BroadcastMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BroadcastMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BroadcastMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = cacheInvalidation_.toBuilder();
              }
              cacheInvalidation_ = input.readMessage(org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cacheInvalidation_);
                cacheInvalidation_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.Broadcast.internal_static_BroadcastMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tdmx.server.pcs.protobuf.Broadcast.internal_static_BroadcastMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage.class, org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BroadcastMessage> PARSER =
        new com.google.protobuf.AbstractParser<BroadcastMessage>() {
      public BroadcastMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BroadcastMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BroadcastMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CACHEINVALIDATION_FIELD_NUMBER = 1;
    private org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage cacheInvalidation_;
    /**
     * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
     */
    public boolean hasCacheInvalidation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
     */
    public org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage getCacheInvalidation() {
      return cacheInvalidation_;
    }
    /**
     * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
     */
    public org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessageOrBuilder getCacheInvalidationOrBuilder() {
      return cacheInvalidation_;
    }

    private void initFields() {
      cacheInvalidation_ = org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, cacheInvalidation_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cacheInvalidation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BroadcastMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BroadcastMessage)
        org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tdmx.server.pcs.protobuf.Broadcast.internal_static_BroadcastMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tdmx.server.pcs.protobuf.Broadcast.internal_static_BroadcastMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage.class, org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage.Builder.class);
      }

      // Construct using org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCacheInvalidationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (cacheInvalidationBuilder_ == null) {
          cacheInvalidation_ = org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.getDefaultInstance();
        } else {
          cacheInvalidationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tdmx.server.pcs.protobuf.Broadcast.internal_static_BroadcastMessage_descriptor;
      }

      public org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage getDefaultInstanceForType() {
        return org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage.getDefaultInstance();
      }

      public org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage build() {
        org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage buildPartial() {
        org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage result = new org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (cacheInvalidationBuilder_ == null) {
          result.cacheInvalidation_ = cacheInvalidation_;
        } else {
          result.cacheInvalidation_ = cacheInvalidationBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage) {
          return mergeFrom((org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage other) {
        if (other == org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage.getDefaultInstance()) return this;
        if (other.hasCacheInvalidation()) {
          mergeCacheInvalidation(other.getCacheInvalidation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tdmx.server.pcs.protobuf.Broadcast.BroadcastMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage cacheInvalidation_ = org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage, org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.Builder, org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessageOrBuilder> cacheInvalidationBuilder_;
      /**
       * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
       */
      public boolean hasCacheInvalidation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
       */
      public org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage getCacheInvalidation() {
        if (cacheInvalidationBuilder_ == null) {
          return cacheInvalidation_;
        } else {
          return cacheInvalidationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
       */
      public Builder setCacheInvalidation(org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage value) {
        if (cacheInvalidationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cacheInvalidation_ = value;
          onChanged();
        } else {
          cacheInvalidationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
       */
      public Builder setCacheInvalidation(
          org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.Builder builderForValue) {
        if (cacheInvalidationBuilder_ == null) {
          cacheInvalidation_ = builderForValue.build();
          onChanged();
        } else {
          cacheInvalidationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
       */
      public Builder mergeCacheInvalidation(org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage value) {
        if (cacheInvalidationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              cacheInvalidation_ != org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.getDefaultInstance()) {
            cacheInvalidation_ =
              org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.newBuilder(cacheInvalidation_).mergeFrom(value).buildPartial();
          } else {
            cacheInvalidation_ = value;
          }
          onChanged();
        } else {
          cacheInvalidationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
       */
      public Builder clearCacheInvalidation() {
        if (cacheInvalidationBuilder_ == null) {
          cacheInvalidation_ = org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.getDefaultInstance();
          onChanged();
        } else {
          cacheInvalidationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
       */
      public org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.Builder getCacheInvalidationBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCacheInvalidationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
       */
      public org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessageOrBuilder getCacheInvalidationOrBuilder() {
        if (cacheInvalidationBuilder_ != null) {
          return cacheInvalidationBuilder_.getMessageOrBuilder();
        } else {
          return cacheInvalidation_;
        }
      }
      /**
       * <code>optional .CacheInvalidationMessage cacheInvalidation = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage, org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.Builder, org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessageOrBuilder> 
          getCacheInvalidationFieldBuilder() {
        if (cacheInvalidationBuilder_ == null) {
          cacheInvalidationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage, org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.Builder, org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessageOrBuilder>(
                  getCacheInvalidation(),
                  getParentForChildren(),
                  isClean());
          cacheInvalidation_ = null;
        }
        return cacheInvalidationBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:BroadcastMessage)
    }

    static {
      defaultInstance = new BroadcastMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BroadcastMessage)
  }

  public interface CacheInvalidationMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CacheInvalidationMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string cacheKey = 2;</code>
     */
    boolean hasCacheKey();
    /**
     * <code>optional string cacheKey = 2;</code>
     */
    java.lang.String getCacheKey();
    /**
     * <code>optional string cacheKey = 2;</code>
     */
    com.google.protobuf.ByteString
        getCacheKeyBytes();
  }
  /**
   * Protobuf type {@code CacheInvalidationMessage}
   */
  public static final class CacheInvalidationMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CacheInvalidationMessage)
      CacheInvalidationMessageOrBuilder {
    // Use CacheInvalidationMessage.newBuilder() to construct.
    private CacheInvalidationMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CacheInvalidationMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CacheInvalidationMessage defaultInstance;
    public static CacheInvalidationMessage getDefaultInstance() {
      return defaultInstance;
    }

    public CacheInvalidationMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CacheInvalidationMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              cacheKey_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.Broadcast.internal_static_CacheInvalidationMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tdmx.server.pcs.protobuf.Broadcast.internal_static_CacheInvalidationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.class, org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<CacheInvalidationMessage> PARSER =
        new com.google.protobuf.AbstractParser<CacheInvalidationMessage>() {
      public CacheInvalidationMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CacheInvalidationMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CacheInvalidationMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CACHEKEY_FIELD_NUMBER = 2;
    private java.lang.Object cacheKey_;
    /**
     * <code>optional string cacheKey = 2;</code>
     */
    public boolean hasCacheKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string cacheKey = 2;</code>
     */
    public java.lang.String getCacheKey() {
      java.lang.Object ref = cacheKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cacheKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cacheKey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCacheKeyBytes() {
      java.lang.Object ref = cacheKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cacheKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      cacheKey_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCacheKeyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCacheKeyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CacheInvalidationMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CacheInvalidationMessage)
        org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tdmx.server.pcs.protobuf.Broadcast.internal_static_CacheInvalidationMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tdmx.server.pcs.protobuf.Broadcast.internal_static_CacheInvalidationMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.class, org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.Builder.class);
      }

      // Construct using org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cacheKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tdmx.server.pcs.protobuf.Broadcast.internal_static_CacheInvalidationMessage_descriptor;
      }

      public org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage getDefaultInstanceForType() {
        return org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.getDefaultInstance();
      }

      public org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage build() {
        org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage buildPartial() {
        org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage result = new org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cacheKey_ = cacheKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage) {
          return mergeFrom((org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage other) {
        if (other == org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCacheKey()) {
          bitField0_ |= 0x00000002;
          cacheKey_ = other.cacheKey_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tdmx.server.pcs.protobuf.Broadcast.CacheInvalidationMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cacheKey_ = "";
      /**
       * <code>optional string cacheKey = 2;</code>
       */
      public boolean hasCacheKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string cacheKey = 2;</code>
       */
      public java.lang.String getCacheKey() {
        java.lang.Object ref = cacheKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cacheKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cacheKey = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCacheKeyBytes() {
        java.lang.Object ref = cacheKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cacheKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cacheKey = 2;</code>
       */
      public Builder setCacheKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cacheKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cacheKey = 2;</code>
       */
      public Builder clearCacheKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cacheKey_ = getDefaultInstance().getCacheKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cacheKey = 2;</code>
       */
      public Builder setCacheKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cacheKey_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CacheInvalidationMessage)
    }

    static {
      defaultInstance = new CacheInvalidationMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CacheInvalidationMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BroadcastMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BroadcastMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CacheInvalidationMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CacheInvalidationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017broadcast.proto\"H\n\020BroadcastMessage\0224\n" +
      "\021cacheInvalidation\030\001 \001(\0132\031.CacheInvalida" +
      "tionMessage\"8\n\030CacheInvalidationMessage\022" +
      "\n\n\002id\030\001 \001(\t\022\020\n\010cacheKey\030\002 \001(\tB)\n\034org.tdm" +
      "x.server.pcs.protobufB\tBroadcast"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BroadcastMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BroadcastMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BroadcastMessage_descriptor,
        new java.lang.String[] { "CacheInvalidation", });
    internal_static_CacheInvalidationMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CacheInvalidationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CacheInvalidationMessage_descriptor,
        new java.lang.String[] { "Id", "CacheKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
