// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache.proto

package org.tdmx.server.pcs.protobuf;

public final class Cache {
  private Cache() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code CacheName}
   */
  public enum CacheName
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DnsResolverGroup = 0;</code>
     */
    DnsResolverGroup(0, 0),
    /**
     * <code>TrustStore = 1;</code>
     */
    TrustStore(1, 1),
    /**
     * <code>DatabasePartition = 2;</code>
     */
    DatabasePartition(2, 2),
    ;

    /**
     * <code>DnsResolverGroup = 0;</code>
     */
    public static final int DnsResolverGroup_VALUE = 0;
    /**
     * <code>TrustStore = 1;</code>
     */
    public static final int TrustStore_VALUE = 1;
    /**
     * <code>DatabasePartition = 2;</code>
     */
    public static final int DatabasePartition_VALUE = 2;


    public final int getNumber() { return value; }

    public static CacheName valueOf(int value) {
      switch (value) {
        case 0: return DnsResolverGroup;
        case 1: return TrustStore;
        case 2: return DatabasePartition;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CacheName>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CacheName>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CacheName>() {
            public CacheName findValueByNumber(int number) {
              return CacheName.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.Cache.getDescriptor().getEnumTypes().get(0);
    }

    private static final CacheName[] VALUES = values();

    public static CacheName valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CacheName(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CacheName)
  }

  public interface InvalidateCacheRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InvalidateCacheRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required .CacheName cacheName = 2;</code>
     */
    boolean hasCacheName();
    /**
     * <code>required .CacheName cacheName = 2;</code>
     */
    org.tdmx.server.pcs.protobuf.Cache.CacheName getCacheName();

    /**
     * <code>optional string keyValue = 3;</code>
     */
    boolean hasKeyValue();
    /**
     * <code>optional string keyValue = 3;</code>
     */
    java.lang.String getKeyValue();
    /**
     * <code>optional string keyValue = 3;</code>
     */
    com.google.protobuf.ByteString
        getKeyValueBytes();
  }
  /**
   * Protobuf type {@code InvalidateCacheRequest}
   *
   * <pre>
   * PCS servers and all PCS clients implement "cacheInvalidation" methods
   * </pre>
   */
  public static final class InvalidateCacheRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:InvalidateCacheRequest)
      InvalidateCacheRequestOrBuilder {
    // Use InvalidateCacheRequest.newBuilder() to construct.
    private InvalidateCacheRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InvalidateCacheRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InvalidateCacheRequest defaultInstance;
    public static InvalidateCacheRequest getDefaultInstance() {
      return defaultInstance;
    }

    public InvalidateCacheRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InvalidateCacheRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.tdmx.server.pcs.protobuf.Cache.CacheName value = org.tdmx.server.pcs.protobuf.Cache.CacheName.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                cacheName_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              keyValue_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.Cache.internal_static_InvalidateCacheRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tdmx.server.pcs.protobuf.Cache.internal_static_InvalidateCacheRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest.class, org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<InvalidateCacheRequest> PARSER =
        new com.google.protobuf.AbstractParser<InvalidateCacheRequest>() {
      public InvalidateCacheRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InvalidateCacheRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InvalidateCacheRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CACHENAME_FIELD_NUMBER = 2;
    private org.tdmx.server.pcs.protobuf.Cache.CacheName cacheName_;
    /**
     * <code>required .CacheName cacheName = 2;</code>
     */
    public boolean hasCacheName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .CacheName cacheName = 2;</code>
     */
    public org.tdmx.server.pcs.protobuf.Cache.CacheName getCacheName() {
      return cacheName_;
    }

    public static final int KEYVALUE_FIELD_NUMBER = 3;
    private java.lang.Object keyValue_;
    /**
     * <code>optional string keyValue = 3;</code>
     */
    public boolean hasKeyValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string keyValue = 3;</code>
     */
    public java.lang.String getKeyValue() {
      java.lang.Object ref = keyValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          keyValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string keyValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKeyValueBytes() {
      java.lang.Object ref = keyValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      cacheName_ = org.tdmx.server.pcs.protobuf.Cache.CacheName.DnsResolverGroup;
      keyValue_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCacheName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, cacheName_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getKeyValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, cacheName_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getKeyValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InvalidateCacheRequest}
     *
     * <pre>
     * PCS servers and all PCS clients implement "cacheInvalidation" methods
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InvalidateCacheRequest)
        org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tdmx.server.pcs.protobuf.Cache.internal_static_InvalidateCacheRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tdmx.server.pcs.protobuf.Cache.internal_static_InvalidateCacheRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest.class, org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest.Builder.class);
      }

      // Construct using org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cacheName_ = org.tdmx.server.pcs.protobuf.Cache.CacheName.DnsResolverGroup;
        bitField0_ = (bitField0_ & ~0x00000002);
        keyValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tdmx.server.pcs.protobuf.Cache.internal_static_InvalidateCacheRequest_descriptor;
      }

      public org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest getDefaultInstanceForType() {
        return org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest.getDefaultInstance();
      }

      public org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest build() {
        org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest buildPartial() {
        org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest result = new org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cacheName_ = cacheName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.keyValue_ = keyValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest) {
          return mergeFrom((org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest other) {
        if (other == org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCacheName()) {
          setCacheName(other.getCacheName());
        }
        if (other.hasKeyValue()) {
          bitField0_ |= 0x00000004;
          keyValue_ = other.keyValue_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasCacheName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private org.tdmx.server.pcs.protobuf.Cache.CacheName cacheName_ = org.tdmx.server.pcs.protobuf.Cache.CacheName.DnsResolverGroup;
      /**
       * <code>required .CacheName cacheName = 2;</code>
       */
      public boolean hasCacheName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .CacheName cacheName = 2;</code>
       */
      public org.tdmx.server.pcs.protobuf.Cache.CacheName getCacheName() {
        return cacheName_;
      }
      /**
       * <code>required .CacheName cacheName = 2;</code>
       */
      public Builder setCacheName(org.tdmx.server.pcs.protobuf.Cache.CacheName value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        cacheName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .CacheName cacheName = 2;</code>
       */
      public Builder clearCacheName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cacheName_ = org.tdmx.server.pcs.protobuf.Cache.CacheName.DnsResolverGroup;
        onChanged();
        return this;
      }

      private java.lang.Object keyValue_ = "";
      /**
       * <code>optional string keyValue = 3;</code>
       */
      public boolean hasKeyValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string keyValue = 3;</code>
       */
      public java.lang.String getKeyValue() {
        java.lang.Object ref = keyValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            keyValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string keyValue = 3;</code>
       */
      public com.google.protobuf.ByteString
          getKeyValueBytes() {
        java.lang.Object ref = keyValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string keyValue = 3;</code>
       */
      public Builder setKeyValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        keyValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string keyValue = 3;</code>
       */
      public Builder clearKeyValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        keyValue_ = getDefaultInstance().getKeyValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string keyValue = 3;</code>
       */
      public Builder setKeyValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        keyValue_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InvalidateCacheRequest)
    }

    static {
      defaultInstance = new InvalidateCacheRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:InvalidateCacheRequest)
  }

  public interface InvalidateCacheResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InvalidateCacheResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool success = 1;</code>
     */
    boolean hasSuccess();
    /**
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code InvalidateCacheResponse}
   */
  public static final class InvalidateCacheResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:InvalidateCacheResponse)
      InvalidateCacheResponseOrBuilder {
    // Use InvalidateCacheResponse.newBuilder() to construct.
    private InvalidateCacheResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InvalidateCacheResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InvalidateCacheResponse defaultInstance;
    public static InvalidateCacheResponse getDefaultInstance() {
      return defaultInstance;
    }

    public InvalidateCacheResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InvalidateCacheResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.Cache.internal_static_InvalidateCacheResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tdmx.server.pcs.protobuf.Cache.internal_static_InvalidateCacheResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.class, org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<InvalidateCacheResponse> PARSER =
        new com.google.protobuf.AbstractParser<InvalidateCacheResponse>() {
      public InvalidateCacheResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InvalidateCacheResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InvalidateCacheResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private void initFields() {
      success_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, success_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InvalidateCacheResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InvalidateCacheResponse)
        org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tdmx.server.pcs.protobuf.Cache.internal_static_InvalidateCacheResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tdmx.server.pcs.protobuf.Cache.internal_static_InvalidateCacheResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.class, org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.Builder.class);
      }

      // Construct using org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tdmx.server.pcs.protobuf.Cache.internal_static_InvalidateCacheResponse_descriptor;
      }

      public org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse getDefaultInstanceForType() {
        return org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.getDefaultInstance();
      }

      public org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse build() {
        org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse buildPartial() {
        org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse result = new org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.success_ = success_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse) {
          return mergeFrom((org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse other) {
        if (other == org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InvalidateCacheResponse)
    }

    static {
      defaultInstance = new InvalidateCacheResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:InvalidateCacheResponse)
  }

  /**
   * Protobuf service {@code CacheServiceProxy}
   */
  public static abstract class CacheServiceProxy
      implements com.google.protobuf.Service {
    protected CacheServiceProxy() {}

    public interface Interface {
      /**
       * <code>rpc invalidateCache(.InvalidateCacheRequest) returns (.InvalidateCacheResponse);</code>
       *
       * <pre>
       * any-&gt;PCS-&gt;all
       * </pre>
       */
      public abstract void invalidateCache(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest request,
          com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CacheServiceProxy() {
        @java.lang.Override
        public  void invalidateCache(
            com.google.protobuf.RpcController controller,
            org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest request,
            com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse> done) {
          impl.invalidateCache(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.invalidateCache(controller, (org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc invalidateCache(.InvalidateCacheRequest) returns (.InvalidateCacheResponse);</code>
     *
     * <pre>
     * any-&gt;PCS-&gt;all
     * </pre>
     */
    public abstract void invalidateCache(
        com.google.protobuf.RpcController controller,
        org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest request,
        com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.Cache.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.invalidateCache(controller, (org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest)request,
            com.google.protobuf.RpcUtil.<org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.tdmx.server.pcs.protobuf.Cache.CacheServiceProxy implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void invalidateCache(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest request,
          com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.class,
            org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse invalidateCache(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse invalidateCache(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.tdmx.server.pcs.protobuf.Cache.InvalidateCacheResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:CacheServiceProxy)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InvalidateCacheRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InvalidateCacheRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InvalidateCacheResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InvalidateCacheResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013cache.proto\"U\n\026InvalidateCacheRequest\022" +
      "\n\n\002id\030\001 \002(\t\022\035\n\tcacheName\030\002 \002(\0162\n.CacheNa" +
      "me\022\020\n\010keyValue\030\003 \001(\t\"*\n\027InvalidateCacheR" +
      "esponse\022\017\n\007success\030\001 \001(\010*H\n\tCacheName\022\024\n" +
      "\020DnsResolverGroup\020\000\022\016\n\nTrustStore\020\001\022\025\n\021D" +
      "atabasePartition\020\0022Y\n\021CacheServiceProxy\022" +
      "D\n\017invalidateCache\022\027.InvalidateCacheRequ" +
      "est\032\030.InvalidateCacheResponseB(\n\034org.tdm" +
      "x.server.pcs.protobufB\005Cache\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_InvalidateCacheRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InvalidateCacheRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_InvalidateCacheRequest_descriptor,
        new java.lang.String[] { "Id", "CacheName", "KeyValue", });
    internal_static_InvalidateCacheResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_InvalidateCacheResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_InvalidateCacheResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
