// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ros-server.proto

package org.tdmx.server.pcs.protobuf;

public final class ROSServer {
  private ROSServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RelayRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RelayRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string domain = 1;</code>
     */
    boolean hasDomain();
    /**
     * <code>optional string domain = 1;</code>
     */
    java.lang.String getDomain();
    /**
     * <code>optional string domain = 1;</code>
     */
    com.google.protobuf.ByteString
        getDomainBytes();

    /**
     * <code>optional string channelKey = 2;</code>
     *
     * <pre>
     * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
     * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
     * </pre>
     */
    boolean hasChannelKey();
    /**
     * <code>optional string channelKey = 2;</code>
     *
     * <pre>
     * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
     * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
     * </pre>
     */
    java.lang.String getChannelKey();
    /**
     * <code>optional string channelKey = 2;</code>
     *
     * <pre>
     * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
     * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
     * </pre>
     */
    com.google.protobuf.ByteString
        getChannelKeyBytes();

    /**
     * <code>optional .RelayRequest.RelayType relayType = 3;</code>
     */
    boolean hasRelayType();
    /**
     * <code>optional .RelayRequest.RelayType relayType = 3;</code>
     */
    org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType getRelayType();

    /**
     * <code>repeated .AttributeValue attribute = 4;</code>
     */
    java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue> 
        getAttributeList();
    /**
     * <code>repeated .AttributeValue attribute = 4;</code>
     */
    org.tdmx.server.pcs.protobuf.Common.AttributeValue getAttribute(int index);
    /**
     * <code>repeated .AttributeValue attribute = 4;</code>
     */
    int getAttributeCount();
    /**
     * <code>repeated .AttributeValue attribute = 4;</code>
     */
    java.util.List<? extends org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder> 
        getAttributeOrBuilderList();
    /**
     * <code>repeated .AttributeValue attribute = 4;</code>
     */
    org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder getAttributeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code RelayRequest}
   */
  public static final class RelayRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RelayRequest)
      RelayRequestOrBuilder {
    // Use RelayRequest.newBuilder() to construct.
    private RelayRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RelayRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RelayRequest defaultInstance;
    public static RelayRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RelayRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RelayRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              domain_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              channelKey_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType value = org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                relayType_ = value;
              }
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                attribute_ = new java.util.ArrayList<org.tdmx.server.pcs.protobuf.Common.AttributeValue>();
                mutable_bitField0_ |= 0x00000008;
              }
              attribute_.add(input.readMessage(org.tdmx.server.pcs.protobuf.Common.AttributeValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          attribute_ = java.util.Collections.unmodifiableList(attribute_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.ROSServer.internal_static_RelayRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tdmx.server.pcs.protobuf.ROSServer.internal_static_RelayRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.class, org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<RelayRequest> PARSER =
        new com.google.protobuf.AbstractParser<RelayRequest>() {
      public RelayRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RelayRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RelayRequest> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code RelayRequest.RelayType}
     */
    public enum RelayType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Message = 0;</code>
       */
      Message(0, 0),
      /**
       * <code>ChannelAuthorization = 1;</code>
       */
      ChannelAuthorization(1, 1),
      /**
       * <code>DestinationSession = 2;</code>
       */
      DestinationSession(2, 2),
      /**
       * <code>DeliveryReply = 3;</code>
       */
      DeliveryReply(3, 3),
      /**
       * <code>FlowControl = 4;</code>
       */
      FlowControl(4, 4),
      ;

      /**
       * <code>Message = 0;</code>
       */
      public static final int Message_VALUE = 0;
      /**
       * <code>ChannelAuthorization = 1;</code>
       */
      public static final int ChannelAuthorization_VALUE = 1;
      /**
       * <code>DestinationSession = 2;</code>
       */
      public static final int DestinationSession_VALUE = 2;
      /**
       * <code>DeliveryReply = 3;</code>
       */
      public static final int DeliveryReply_VALUE = 3;
      /**
       * <code>FlowControl = 4;</code>
       */
      public static final int FlowControl_VALUE = 4;


      public final int getNumber() { return value; }

      public static RelayType valueOf(int value) {
        switch (value) {
          case 0: return Message;
          case 1: return ChannelAuthorization;
          case 2: return DestinationSession;
          case 3: return DeliveryReply;
          case 4: return FlowControl;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RelayType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RelayType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RelayType>() {
              public RelayType findValueByNumber(int number) {
                return RelayType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final RelayType[] VALUES = values();

      public static RelayType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RelayType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RelayRequest.RelayType)
    }

    private int bitField0_;
    public static final int DOMAIN_FIELD_NUMBER = 1;
    private java.lang.Object domain_;
    /**
     * <code>optional string domain = 1;</code>
     */
    public boolean hasDomain() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string domain = 1;</code>
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          domain_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string domain = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNELKEY_FIELD_NUMBER = 2;
    private java.lang.Object channelKey_;
    /**
     * <code>optional string channelKey = 2;</code>
     *
     * <pre>
     * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
     * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
     * </pre>
     */
    public boolean hasChannelKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string channelKey = 2;</code>
     *
     * <pre>
     * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
     * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
     * </pre>
     */
    public java.lang.String getChannelKey() {
      java.lang.Object ref = channelKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channelKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string channelKey = 2;</code>
     *
     * <pre>
     * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
     * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChannelKeyBytes() {
      java.lang.Object ref = channelKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RELAYTYPE_FIELD_NUMBER = 3;
    private org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType relayType_;
    /**
     * <code>optional .RelayRequest.RelayType relayType = 3;</code>
     */
    public boolean hasRelayType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .RelayRequest.RelayType relayType = 3;</code>
     */
    public org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType getRelayType() {
      return relayType_;
    }

    public static final int ATTRIBUTE_FIELD_NUMBER = 4;
    private java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue> attribute_;
    /**
     * <code>repeated .AttributeValue attribute = 4;</code>
     */
    public java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue> getAttributeList() {
      return attribute_;
    }
    /**
     * <code>repeated .AttributeValue attribute = 4;</code>
     */
    public java.util.List<? extends org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder> 
        getAttributeOrBuilderList() {
      return attribute_;
    }
    /**
     * <code>repeated .AttributeValue attribute = 4;</code>
     */
    public int getAttributeCount() {
      return attribute_.size();
    }
    /**
     * <code>repeated .AttributeValue attribute = 4;</code>
     */
    public org.tdmx.server.pcs.protobuf.Common.AttributeValue getAttribute(int index) {
      return attribute_.get(index);
    }
    /**
     * <code>repeated .AttributeValue attribute = 4;</code>
     */
    public org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder getAttributeOrBuilder(
        int index) {
      return attribute_.get(index);
    }

    private void initFields() {
      domain_ = "";
      channelKey_ = "";
      relayType_ = org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType.Message;
      attribute_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getAttributeCount(); i++) {
        if (!getAttribute(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDomainBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getChannelKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, relayType_.getNumber());
      }
      for (int i = 0; i < attribute_.size(); i++) {
        output.writeMessage(4, attribute_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDomainBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getChannelKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, relayType_.getNumber());
      }
      for (int i = 0; i < attribute_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, attribute_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RelayRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RelayRequest)
        org.tdmx.server.pcs.protobuf.ROSServer.RelayRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tdmx.server.pcs.protobuf.ROSServer.internal_static_RelayRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tdmx.server.pcs.protobuf.ROSServer.internal_static_RelayRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.class, org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.Builder.class);
      }

      // Construct using org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttributeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        domain_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        channelKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        relayType_ = org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType.Message;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (attributeBuilder_ == null) {
          attribute_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          attributeBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tdmx.server.pcs.protobuf.ROSServer.internal_static_RelayRequest_descriptor;
      }

      public org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest getDefaultInstanceForType() {
        return org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.getDefaultInstance();
      }

      public org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest build() {
        org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest buildPartial() {
        org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest result = new org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.domain_ = domain_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channelKey_ = channelKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.relayType_ = relayType_;
        if (attributeBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            attribute_ = java.util.Collections.unmodifiableList(attribute_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.attribute_ = attribute_;
        } else {
          result.attribute_ = attributeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest) {
          return mergeFrom((org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest other) {
        if (other == org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.getDefaultInstance()) return this;
        if (other.hasDomain()) {
          bitField0_ |= 0x00000001;
          domain_ = other.domain_;
          onChanged();
        }
        if (other.hasChannelKey()) {
          bitField0_ |= 0x00000002;
          channelKey_ = other.channelKey_;
          onChanged();
        }
        if (other.hasRelayType()) {
          setRelayType(other.getRelayType());
        }
        if (attributeBuilder_ == null) {
          if (!other.attribute_.isEmpty()) {
            if (attribute_.isEmpty()) {
              attribute_ = other.attribute_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAttributeIsMutable();
              attribute_.addAll(other.attribute_);
            }
            onChanged();
          }
        } else {
          if (!other.attribute_.isEmpty()) {
            if (attributeBuilder_.isEmpty()) {
              attributeBuilder_.dispose();
              attributeBuilder_ = null;
              attribute_ = other.attribute_;
              bitField0_ = (bitField0_ & ~0x00000008);
              attributeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttributeFieldBuilder() : null;
            } else {
              attributeBuilder_.addAllMessages(other.attribute_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAttributeCount(); i++) {
          if (!getAttribute(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object domain_ = "";
      /**
       * <code>optional string domain = 1;</code>
       */
      public boolean hasDomain() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string domain = 1;</code>
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            domain_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string domain = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string domain = 1;</code>
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string domain = 1;</code>
       */
      public Builder clearDomain() {
        bitField0_ = (bitField0_ & ~0x00000001);
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <code>optional string domain = 1;</code>
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        domain_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object channelKey_ = "";
      /**
       * <code>optional string channelKey = 2;</code>
       *
       * <pre>
       * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
       * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
       * </pre>
       */
      public boolean hasChannelKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string channelKey = 2;</code>
       *
       * <pre>
       * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
       * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
       * </pre>
       */
      public java.lang.String getChannelKey() {
        java.lang.Object ref = channelKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channelKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string channelKey = 2;</code>
       *
       * <pre>
       * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
       * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
       * </pre>
       */
      public com.google.protobuf.ByteString
          getChannelKeyBytes() {
        java.lang.Object ref = channelKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channelKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string channelKey = 2;</code>
       *
       * <pre>
       * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
       * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
       * </pre>
       */
      public Builder setChannelKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        channelKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string channelKey = 2;</code>
       *
       * <pre>
       * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
       * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
       * </pre>
       */
      public Builder clearChannelKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channelKey_ = getDefaultInstance().getChannelKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string channelKey = 2;</code>
       *
       * <pre>
       * channelKey (originating) originLocalName&#64;originDomain-&gt;destLocalName&#64;destDomain#destService
       * channelKey (destination) destLocalName&#64;destDomain#destService-&gt;originLocalName&#64;originDomain
       * </pre>
       */
      public Builder setChannelKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        channelKey_ = value;
        onChanged();
        return this;
      }

      private org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType relayType_ = org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType.Message;
      /**
       * <code>optional .RelayRequest.RelayType relayType = 3;</code>
       */
      public boolean hasRelayType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .RelayRequest.RelayType relayType = 3;</code>
       */
      public org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType getRelayType() {
        return relayType_;
      }
      /**
       * <code>optional .RelayRequest.RelayType relayType = 3;</code>
       */
      public Builder setRelayType(org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        relayType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .RelayRequest.RelayType relayType = 3;</code>
       */
      public Builder clearRelayType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        relayType_ = org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.RelayType.Message;
        onChanged();
        return this;
      }

      private java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue> attribute_ =
        java.util.Collections.emptyList();
      private void ensureAttributeIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          attribute_ = new java.util.ArrayList<org.tdmx.server.pcs.protobuf.Common.AttributeValue>(attribute_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.tdmx.server.pcs.protobuf.Common.AttributeValue, org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder, org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder> attributeBuilder_;

      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue> getAttributeList() {
        if (attributeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attribute_);
        } else {
          return attributeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public int getAttributeCount() {
        if (attributeBuilder_ == null) {
          return attribute_.size();
        } else {
          return attributeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public org.tdmx.server.pcs.protobuf.Common.AttributeValue getAttribute(int index) {
        if (attributeBuilder_ == null) {
          return attribute_.get(index);
        } else {
          return attributeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public Builder setAttribute(
          int index, org.tdmx.server.pcs.protobuf.Common.AttributeValue value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.set(index, value);
          onChanged();
        } else {
          attributeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public Builder setAttribute(
          int index, org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public Builder addAttribute(org.tdmx.server.pcs.protobuf.Common.AttributeValue value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.add(value);
          onChanged();
        } else {
          attributeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public Builder addAttribute(
          int index, org.tdmx.server.pcs.protobuf.Common.AttributeValue value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.add(index, value);
          onChanged();
        } else {
          attributeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public Builder addAttribute(
          org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.add(builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public Builder addAttribute(
          int index, org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public Builder addAllAttribute(
          java.lang.Iterable<? extends org.tdmx.server.pcs.protobuf.Common.AttributeValue> values) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attribute_);
          onChanged();
        } else {
          attributeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public Builder clearAttribute() {
        if (attributeBuilder_ == null) {
          attribute_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          attributeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public Builder removeAttribute(int index) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.remove(index);
          onChanged();
        } else {
          attributeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder getAttributeBuilder(
          int index) {
        return getAttributeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder getAttributeOrBuilder(
          int index) {
        if (attributeBuilder_ == null) {
          return attribute_.get(index);  } else {
          return attributeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public java.util.List<? extends org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder> 
           getAttributeOrBuilderList() {
        if (attributeBuilder_ != null) {
          return attributeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attribute_);
        }
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder addAttributeBuilder() {
        return getAttributeFieldBuilder().addBuilder(
            org.tdmx.server.pcs.protobuf.Common.AttributeValue.getDefaultInstance());
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder addAttributeBuilder(
          int index) {
        return getAttributeFieldBuilder().addBuilder(
            index, org.tdmx.server.pcs.protobuf.Common.AttributeValue.getDefaultInstance());
      }
      /**
       * <code>repeated .AttributeValue attribute = 4;</code>
       */
      public java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder> 
           getAttributeBuilderList() {
        return getAttributeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.tdmx.server.pcs.protobuf.Common.AttributeValue, org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder, org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder> 
          getAttributeFieldBuilder() {
        if (attributeBuilder_ == null) {
          attributeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.tdmx.server.pcs.protobuf.Common.AttributeValue, org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder, org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder>(
                  attribute_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          attribute_ = null;
        }
        return attributeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:RelayRequest)
    }

    static {
      defaultInstance = new RelayRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RelayRequest)
  }

  public interface RelayResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RelayResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code RelayResponse}
   */
  public static final class RelayResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RelayResponse)
      RelayResponseOrBuilder {
    // Use RelayResponse.newBuilder() to construct.
    private RelayResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RelayResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RelayResponse defaultInstance;
    public static RelayResponse getDefaultInstance() {
      return defaultInstance;
    }

    public RelayResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RelayResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.ROSServer.internal_static_RelayResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tdmx.server.pcs.protobuf.ROSServer.internal_static_RelayResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.class, org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<RelayResponse> PARSER =
        new com.google.protobuf.AbstractParser<RelayResponse>() {
      public RelayResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RelayResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RelayResponse> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RelayResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RelayResponse)
        org.tdmx.server.pcs.protobuf.ROSServer.RelayResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tdmx.server.pcs.protobuf.ROSServer.internal_static_RelayResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tdmx.server.pcs.protobuf.ROSServer.internal_static_RelayResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.class, org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.Builder.class);
      }

      // Construct using org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tdmx.server.pcs.protobuf.ROSServer.internal_static_RelayResponse_descriptor;
      }

      public org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse getDefaultInstanceForType() {
        return org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.getDefaultInstance();
      }

      public org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse build() {
        org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse buildPartial() {
        org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse result = new org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse) {
          return mergeFrom((org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse other) {
        if (other == org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RelayResponse)
    }

    static {
      defaultInstance = new RelayResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RelayResponse)
  }

  /**
   * Protobuf service {@code RelayOutboundServiceProxy}
   */
  public static abstract class RelayOutboundServiceProxy
      implements com.google.protobuf.Service {
    protected RelayOutboundServiceProxy() {}

    public interface Interface {
      /**
       * <code>rpc relay(.RelayRequest) returns (.RelayResponse);</code>
       */
      public abstract void relay(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest request,
          com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new RelayOutboundServiceProxy() {
        @java.lang.Override
        public  void relay(
            com.google.protobuf.RpcController controller,
            org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest request,
            com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse> done) {
          impl.relay(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.relay(controller, (org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc relay(.RelayRequest) returns (.RelayResponse);</code>
     */
    public abstract void relay(
        com.google.protobuf.RpcController controller,
        org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest request,
        com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.ROSServer.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.relay(controller, (org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest)request,
            com.google.protobuf.RpcUtil.<org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.tdmx.server.pcs.protobuf.ROSServer.RelayOutboundServiceProxy implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void relay(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest request,
          com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.class,
            org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse relay(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse relay(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.ROSServer.RelayRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.tdmx.server.pcs.protobuf.ROSServer.RelayResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:RelayOutboundServiceProxy)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RelayRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RelayRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RelayResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RelayResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ros-server.proto\032\014common.proto\"\362\001\n\014Rel" +
      "ayRequest\022\016\n\006domain\030\001 \001(\t\022\022\n\nchannelKey\030" +
      "\002 \001(\t\022*\n\trelayType\030\003 \001(\0162\027.RelayRequest." +
      "RelayType\022\"\n\tattribute\030\004 \003(\0132\017.Attribute" +
      "Value\"n\n\tRelayType\022\013\n\007Message\020\000\022\030\n\024Chann" +
      "elAuthorization\020\001\022\026\n\022DestinationSession\020" +
      "\002\022\021\n\rDeliveryReply\020\003\022\017\n\013FlowControl\020\004\"\017\n" +
      "\rRelayResponse2C\n\031RelayOutboundServicePr" +
      "oxy\022&\n\005relay\022\r.RelayRequest\032\016.RelayRespo" +
      "nseB,\n\034org.tdmx.server.pcs.protobufB\tROS",
      "Server\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tdmx.server.pcs.protobuf.Common.getDescriptor(),
        }, assigner);
    internal_static_RelayRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RelayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RelayRequest_descriptor,
        new java.lang.String[] { "Domain", "ChannelKey", "RelayType", "Attribute", });
    internal_static_RelayResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RelayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RelayResponse_descriptor,
        new java.lang.String[] { });
    org.tdmx.server.pcs.protobuf.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
