// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tos-server.proto

package org.tdmx.server.pcs.protobuf;

public final class TOSServer {
  private TOSServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TransferRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransferRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string segment = 1;</code>
     */
    boolean hasSegment();
    /**
     * <code>optional string segment = 1;</code>
     */
    java.lang.String getSegment();
    /**
     * <code>optional string segment = 1;</code>
     */
    com.google.protobuf.ByteString
        getSegmentBytes();

    /**
     * <code>optional string apiName = 2;</code>
     */
    boolean hasApiName();
    /**
     * <code>optional string apiName = 2;</code>
     */
    java.lang.String getApiName();
    /**
     * <code>optional string apiName = 2;</code>
     */
    com.google.protobuf.ByteString
        getApiNameBytes();

    /**
     * <code>optional string sessionId = 3;</code>
     */
    boolean hasSessionId();
    /**
     * <code>optional string sessionId = 3;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>optional string sessionId = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>optional .ObjectType transferType = 4;</code>
     */
    boolean hasTransferType();
    /**
     * <code>optional .ObjectType transferType = 4;</code>
     */
    org.tdmx.server.pcs.protobuf.Common.ObjectType getTransferType();

    /**
     * <code>repeated .AttributeValue attribute = 5;</code>
     */
    java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue> 
        getAttributeList();
    /**
     * <code>repeated .AttributeValue attribute = 5;</code>
     */
    org.tdmx.server.pcs.protobuf.Common.AttributeValue getAttribute(int index);
    /**
     * <code>repeated .AttributeValue attribute = 5;</code>
     */
    int getAttributeCount();
    /**
     * <code>repeated .AttributeValue attribute = 5;</code>
     */
    java.util.List<? extends org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder> 
        getAttributeOrBuilderList();
    /**
     * <code>repeated .AttributeValue attribute = 5;</code>
     */
    org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder getAttributeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TransferRequest}
   */
  public static final class TransferRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TransferRequest)
      TransferRequestOrBuilder {
    // Use TransferRequest.newBuilder() to construct.
    private TransferRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TransferRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TransferRequest defaultInstance;
    public static TransferRequest getDefaultInstance() {
      return defaultInstance;
    }

    public TransferRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TransferRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              segment_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              apiName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              sessionId_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              org.tdmx.server.pcs.protobuf.Common.ObjectType value = org.tdmx.server.pcs.protobuf.Common.ObjectType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                transferType_ = value;
              }
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                attribute_ = new java.util.ArrayList<org.tdmx.server.pcs.protobuf.Common.AttributeValue>();
                mutable_bitField0_ |= 0x00000010;
              }
              attribute_.add(input.readMessage(org.tdmx.server.pcs.protobuf.Common.AttributeValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          attribute_ = java.util.Collections.unmodifiableList(attribute_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.TOSServer.internal_static_TransferRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tdmx.server.pcs.protobuf.TOSServer.internal_static_TransferRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest.class, org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<TransferRequest> PARSER =
        new com.google.protobuf.AbstractParser<TransferRequest>() {
      public TransferRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransferRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TransferRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SEGMENT_FIELD_NUMBER = 1;
    private java.lang.Object segment_;
    /**
     * <code>optional string segment = 1;</code>
     */
    public boolean hasSegment() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string segment = 1;</code>
     */
    public java.lang.String getSegment() {
      java.lang.Object ref = segment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          segment_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string segment = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSegmentBytes() {
      java.lang.Object ref = segment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        segment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APINAME_FIELD_NUMBER = 2;
    private java.lang.Object apiName_;
    /**
     * <code>optional string apiName = 2;</code>
     */
    public boolean hasApiName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string apiName = 2;</code>
     */
    public java.lang.String getApiName() {
      java.lang.Object ref = apiName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          apiName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string apiName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getApiNameBytes() {
      java.lang.Object ref = apiName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apiName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private java.lang.Object sessionId_;
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSFERTYPE_FIELD_NUMBER = 4;
    private org.tdmx.server.pcs.protobuf.Common.ObjectType transferType_;
    /**
     * <code>optional .ObjectType transferType = 4;</code>
     */
    public boolean hasTransferType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .ObjectType transferType = 4;</code>
     */
    public org.tdmx.server.pcs.protobuf.Common.ObjectType getTransferType() {
      return transferType_;
    }

    public static final int ATTRIBUTE_FIELD_NUMBER = 5;
    private java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue> attribute_;
    /**
     * <code>repeated .AttributeValue attribute = 5;</code>
     */
    public java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue> getAttributeList() {
      return attribute_;
    }
    /**
     * <code>repeated .AttributeValue attribute = 5;</code>
     */
    public java.util.List<? extends org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder> 
        getAttributeOrBuilderList() {
      return attribute_;
    }
    /**
     * <code>repeated .AttributeValue attribute = 5;</code>
     */
    public int getAttributeCount() {
      return attribute_.size();
    }
    /**
     * <code>repeated .AttributeValue attribute = 5;</code>
     */
    public org.tdmx.server.pcs.protobuf.Common.AttributeValue getAttribute(int index) {
      return attribute_.get(index);
    }
    /**
     * <code>repeated .AttributeValue attribute = 5;</code>
     */
    public org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder getAttributeOrBuilder(
        int index) {
      return attribute_.get(index);
    }

    private void initFields() {
      segment_ = "";
      apiName_ = "";
      sessionId_ = "";
      transferType_ = org.tdmx.server.pcs.protobuf.Common.ObjectType.Message;
      attribute_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getAttributeCount(); i++) {
        if (!getAttribute(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSegmentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getApiNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, transferType_.getNumber());
      }
      for (int i = 0; i < attribute_.size(); i++) {
        output.writeMessage(5, attribute_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSegmentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getApiNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, transferType_.getNumber());
      }
      for (int i = 0; i < attribute_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, attribute_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransferRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransferRequest)
        org.tdmx.server.pcs.protobuf.TOSServer.TransferRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tdmx.server.pcs.protobuf.TOSServer.internal_static_TransferRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tdmx.server.pcs.protobuf.TOSServer.internal_static_TransferRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest.class, org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest.Builder.class);
      }

      // Construct using org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttributeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        segment_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        apiName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        transferType_ = org.tdmx.server.pcs.protobuf.Common.ObjectType.Message;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (attributeBuilder_ == null) {
          attribute_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          attributeBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tdmx.server.pcs.protobuf.TOSServer.internal_static_TransferRequest_descriptor;
      }

      public org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest getDefaultInstanceForType() {
        return org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest.getDefaultInstance();
      }

      public org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest build() {
        org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest buildPartial() {
        org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest result = new org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.segment_ = segment_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.apiName_ = apiName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.transferType_ = transferType_;
        if (attributeBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            attribute_ = java.util.Collections.unmodifiableList(attribute_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.attribute_ = attribute_;
        } else {
          result.attribute_ = attributeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest) {
          return mergeFrom((org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest other) {
        if (other == org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest.getDefaultInstance()) return this;
        if (other.hasSegment()) {
          bitField0_ |= 0x00000001;
          segment_ = other.segment_;
          onChanged();
        }
        if (other.hasApiName()) {
          bitField0_ |= 0x00000002;
          apiName_ = other.apiName_;
          onChanged();
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000004;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasTransferType()) {
          setTransferType(other.getTransferType());
        }
        if (attributeBuilder_ == null) {
          if (!other.attribute_.isEmpty()) {
            if (attribute_.isEmpty()) {
              attribute_ = other.attribute_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureAttributeIsMutable();
              attribute_.addAll(other.attribute_);
            }
            onChanged();
          }
        } else {
          if (!other.attribute_.isEmpty()) {
            if (attributeBuilder_.isEmpty()) {
              attributeBuilder_.dispose();
              attributeBuilder_ = null;
              attribute_ = other.attribute_;
              bitField0_ = (bitField0_ & ~0x00000010);
              attributeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttributeFieldBuilder() : null;
            } else {
              attributeBuilder_.addAllMessages(other.attribute_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAttributeCount(); i++) {
          if (!getAttribute(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object segment_ = "";
      /**
       * <code>optional string segment = 1;</code>
       */
      public boolean hasSegment() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string segment = 1;</code>
       */
      public java.lang.String getSegment() {
        java.lang.Object ref = segment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            segment_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string segment = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSegmentBytes() {
        java.lang.Object ref = segment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          segment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string segment = 1;</code>
       */
      public Builder setSegment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        segment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string segment = 1;</code>
       */
      public Builder clearSegment() {
        bitField0_ = (bitField0_ & ~0x00000001);
        segment_ = getDefaultInstance().getSegment();
        onChanged();
        return this;
      }
      /**
       * <code>optional string segment = 1;</code>
       */
      public Builder setSegmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        segment_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object apiName_ = "";
      /**
       * <code>optional string apiName = 2;</code>
       */
      public boolean hasApiName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string apiName = 2;</code>
       */
      public java.lang.String getApiName() {
        java.lang.Object ref = apiName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            apiName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string apiName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getApiNameBytes() {
        java.lang.Object ref = apiName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apiName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string apiName = 2;</code>
       */
      public Builder setApiName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        apiName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string apiName = 2;</code>
       */
      public Builder clearApiName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        apiName_ = getDefaultInstance().getApiName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string apiName = 2;</code>
       */
      public Builder setApiNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        apiName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sessionId_ = "";
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sessionId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionId_ = value;
        onChanged();
        return this;
      }

      private org.tdmx.server.pcs.protobuf.Common.ObjectType transferType_ = org.tdmx.server.pcs.protobuf.Common.ObjectType.Message;
      /**
       * <code>optional .ObjectType transferType = 4;</code>
       */
      public boolean hasTransferType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .ObjectType transferType = 4;</code>
       */
      public org.tdmx.server.pcs.protobuf.Common.ObjectType getTransferType() {
        return transferType_;
      }
      /**
       * <code>optional .ObjectType transferType = 4;</code>
       */
      public Builder setTransferType(org.tdmx.server.pcs.protobuf.Common.ObjectType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        transferType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ObjectType transferType = 4;</code>
       */
      public Builder clearTransferType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        transferType_ = org.tdmx.server.pcs.protobuf.Common.ObjectType.Message;
        onChanged();
        return this;
      }

      private java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue> attribute_ =
        java.util.Collections.emptyList();
      private void ensureAttributeIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          attribute_ = new java.util.ArrayList<org.tdmx.server.pcs.protobuf.Common.AttributeValue>(attribute_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.tdmx.server.pcs.protobuf.Common.AttributeValue, org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder, org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder> attributeBuilder_;

      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue> getAttributeList() {
        if (attributeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attribute_);
        } else {
          return attributeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public int getAttributeCount() {
        if (attributeBuilder_ == null) {
          return attribute_.size();
        } else {
          return attributeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public org.tdmx.server.pcs.protobuf.Common.AttributeValue getAttribute(int index) {
        if (attributeBuilder_ == null) {
          return attribute_.get(index);
        } else {
          return attributeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public Builder setAttribute(
          int index, org.tdmx.server.pcs.protobuf.Common.AttributeValue value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.set(index, value);
          onChanged();
        } else {
          attributeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public Builder setAttribute(
          int index, org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public Builder addAttribute(org.tdmx.server.pcs.protobuf.Common.AttributeValue value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.add(value);
          onChanged();
        } else {
          attributeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public Builder addAttribute(
          int index, org.tdmx.server.pcs.protobuf.Common.AttributeValue value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.add(index, value);
          onChanged();
        } else {
          attributeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public Builder addAttribute(
          org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.add(builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public Builder addAttribute(
          int index, org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public Builder addAllAttribute(
          java.lang.Iterable<? extends org.tdmx.server.pcs.protobuf.Common.AttributeValue> values) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attribute_);
          onChanged();
        } else {
          attributeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public Builder clearAttribute() {
        if (attributeBuilder_ == null) {
          attribute_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          attributeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public Builder removeAttribute(int index) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.remove(index);
          onChanged();
        } else {
          attributeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder getAttributeBuilder(
          int index) {
        return getAttributeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder getAttributeOrBuilder(
          int index) {
        if (attributeBuilder_ == null) {
          return attribute_.get(index);  } else {
          return attributeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public java.util.List<? extends org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder> 
           getAttributeOrBuilderList() {
        if (attributeBuilder_ != null) {
          return attributeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attribute_);
        }
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder addAttributeBuilder() {
        return getAttributeFieldBuilder().addBuilder(
            org.tdmx.server.pcs.protobuf.Common.AttributeValue.getDefaultInstance());
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder addAttributeBuilder(
          int index) {
        return getAttributeFieldBuilder().addBuilder(
            index, org.tdmx.server.pcs.protobuf.Common.AttributeValue.getDefaultInstance());
      }
      /**
       * <code>repeated .AttributeValue attribute = 5;</code>
       */
      public java.util.List<org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder> 
           getAttributeBuilderList() {
        return getAttributeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.tdmx.server.pcs.protobuf.Common.AttributeValue, org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder, org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder> 
          getAttributeFieldBuilder() {
        if (attributeBuilder_ == null) {
          attributeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.tdmx.server.pcs.protobuf.Common.AttributeValue, org.tdmx.server.pcs.protobuf.Common.AttributeValue.Builder, org.tdmx.server.pcs.protobuf.Common.AttributeValueOrBuilder>(
                  attribute_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          attribute_ = null;
        }
        return attributeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:TransferRequest)
    }

    static {
      defaultInstance = new TransferRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TransferRequest)
  }

  public interface TransferResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransferResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool success = 1;</code>
     */
    boolean hasSuccess();
    /**
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code TransferResponse}
   */
  public static final class TransferResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TransferResponse)
      TransferResponseOrBuilder {
    // Use TransferResponse.newBuilder() to construct.
    private TransferResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TransferResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TransferResponse defaultInstance;
    public static TransferResponse getDefaultInstance() {
      return defaultInstance;
    }

    public TransferResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TransferResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.TOSServer.internal_static_TransferResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tdmx.server.pcs.protobuf.TOSServer.internal_static_TransferResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.class, org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<TransferResponse> PARSER =
        new com.google.protobuf.AbstractParser<TransferResponse>() {
      public TransferResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransferResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TransferResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private void initFields() {
      success_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, success_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransferResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransferResponse)
        org.tdmx.server.pcs.protobuf.TOSServer.TransferResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tdmx.server.pcs.protobuf.TOSServer.internal_static_TransferResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tdmx.server.pcs.protobuf.TOSServer.internal_static_TransferResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.class, org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.Builder.class);
      }

      // Construct using org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tdmx.server.pcs.protobuf.TOSServer.internal_static_TransferResponse_descriptor;
      }

      public org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse getDefaultInstanceForType() {
        return org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.getDefaultInstance();
      }

      public org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse build() {
        org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse buildPartial() {
        org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse result = new org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.success_ = success_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse) {
          return mergeFrom((org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse other) {
        if (other == org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TransferResponse)
    }

    static {
      defaultInstance = new TransferResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TransferResponse)
  }

  /**
   * Protobuf service {@code TransferObjectServiceProxy}
   */
  public static abstract class TransferObjectServiceProxy
      implements com.google.protobuf.Service {
    protected TransferObjectServiceProxy() {}

    public interface Interface {
      /**
       * <code>rpc transfer(.TransferRequest) returns (.TransferResponse);</code>
       */
      public abstract void transfer(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest request,
          com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new TransferObjectServiceProxy() {
        @java.lang.Override
        public  void transfer(
            com.google.protobuf.RpcController controller,
            org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest request,
            com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse> done) {
          impl.transfer(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.transfer(controller, (org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc transfer(.TransferRequest) returns (.TransferResponse);</code>
     */
    public abstract void transfer(
        com.google.protobuf.RpcController controller,
        org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest request,
        com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.tdmx.server.pcs.protobuf.TOSServer.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.transfer(controller, (org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest)request,
            com.google.protobuf.RpcUtil.<org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.tdmx.server.pcs.protobuf.TOSServer.TransferObjectServiceProxy implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void transfer(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest request,
          com.google.protobuf.RpcCallback<org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.class,
            org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse transfer(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse transfer(
          com.google.protobuf.RpcController controller,
          org.tdmx.server.pcs.protobuf.TOSServer.TransferRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.tdmx.server.pcs.protobuf.TOSServer.TransferResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:TransferObjectServiceProxy)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransferRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TransferRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransferResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TransferResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020tos-server.proto\032\014common.proto\"\215\001\n\017Tra" +
      "nsferRequest\022\017\n\007segment\030\001 \001(\t\022\017\n\007apiName" +
      "\030\002 \001(\t\022\021\n\tsessionId\030\003 \001(\t\022!\n\014transferTyp" +
      "e\030\004 \001(\0162\013.ObjectType\022\"\n\tattribute\030\005 \003(\0132" +
      "\017.AttributeValue\"#\n\020TransferResponse\022\017\n\007" +
      "success\030\001 \001(\0102M\n\032TransferObjectServicePr" +
      "oxy\022/\n\010transfer\022\020.TransferRequest\032\021.Tran" +
      "sferResponseB,\n\034org.tdmx.server.pcs.prot" +
      "obufB\tTOSServer\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tdmx.server.pcs.protobuf.Common.getDescriptor(),
        }, assigner);
    internal_static_TransferRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransferRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TransferRequest_descriptor,
        new java.lang.String[] { "Segment", "ApiName", "SessionId", "TransferType", "Attribute", });
    internal_static_TransferResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TransferResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TransferResponse_descriptor,
        new java.lang.String[] { "Success", });
    org.tdmx.server.pcs.protobuf.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
